version: "3.7"

services:
  mono: &mono_base
    image: mono
    restart: always
    build:
      context: .
    command: ["sleep", "infinity"]
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"