version: "3.7"

services:
  mono:
    image: mono
    restart: always
    build:
      context: .
    volumes:
      - .apprc:/app/.apprc
    secrets:
      - master_key
    logging: &loggin
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
secrets:
  master_key:
    file: ./master_key
